kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "avptest/data/data/test"
type: Opaque
stringData:
  sample-secret: <sample>
  sample-secret-1: <sample>
